#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use FizzBuzz\FizzBuzzCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new FizzBuzzCommand());
$application->run();